# Generated by Django 3.2.5 on 2021-07-31 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210727_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mails',
            field=models.BooleanField(default=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('male', 'Мужской пол'), ('female', 'Женский пол')], default='female', max_length=40),
        ),
    ]
